---
version: "3.9"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - config:/config
    ports:
      - 8080:80
    restart: unless-stopped


volumes:
  config:
